CREATE TABLE [prodcopy].[Team]
(
[administratorid] [uniqueidentifier] NULL,
[administratoridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[administratoridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[businessunitid] [uniqueidentifier] NULL,
[businessunitidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchangerate] [decimal] (28, 0) NULL,
[importsequencenumber] [int] NULL,
[isdefault] [bit] NULL,
[isdefaultname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organizationid] [uniqueidentifier] NULL,
[organizationidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[processid] [uniqueidentifier] NULL,
[queueid] [uniqueidentifier] NULL,
[queueidname] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regardingobjectid] [uniqueidentifier] NULL,
[regardingobjecttypecode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[systemmanaged] [bit] NULL,
[systemmanagedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[teamid] [uniqueidentifier] NOT NULL,
[teamtemplateid] [uniqueidentifier] NULL,
[teamtype] [int] NULL,
[teamtypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[traversedpath] [nvarchar] (1250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[versionnumber] [bigint] NULL,
[yominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Team__copyloadda__5CD6CB2B] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopy].[Team] ADD CONSTRAINT [PK__Team__5ED65F32DBACEED2] PRIMARY KEY CLUSTERED  ([teamid])
GO
