IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\BI Developers')
CREATE LOGIN [SSBINFO\BI Developers] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\BI Developers] FOR LOGIN [SSBINFO\BI Developers] WITH DEFAULT_SCHEMA=[SSBCLOUD\Bi Developers]
GO
GRANT ALTER TO [SSBCLOUD\BI Developers]
GRANT DELETE TO [SSBCLOUD\BI Developers]
GRANT EXECUTE TO [SSBCLOUD\BI Developers]
GRANT INSERT TO [SSBCLOUD\BI Developers]
GRANT SELECT TO [SSBCLOUD\BI Developers]
GRANT UPDATE TO [SSBCLOUD\BI Developers]
